#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1 ) in;

layout(std430, binding = 0) buffer buf
{
	float data[];
};

layout(push_constant, std140) uniform SizeBlock {
	uint test_num;
	float mul;
//	float two;
//	float three;
} p_constants;

void main() {
//	p_constants.two;
//	p_constants.three;

	switch (p_constants.test_num) {
	case 0: {
		// Test 0 does nothing.
	} break;
	case 1: {
		for (int i = 0; i < data.length(); ++i)
		{
			data[i] *= p_constants.mul;
		}
	} break;
	}

}
